apiVersion: apps/v1
kind: Deployment
metadata:
  name: indiaproj-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: indiaproj
  template:
    metadata:
      labels:
        app: indiaproj
    spec:
      containers:
        - name: indiaproj-container
          image: holyyyycow/indiaproj:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
